'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PokemonBattlePredictor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AOT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AOT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AOT2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AOT2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AOT3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AOT3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to id,identifier,generation_id,type_id,power,pp,accuracy,priority,target_id,damage_class_id,effect_id,effect_chance,contest_type_id,contest_effect_id,super_contest_effect_id
        '''1,pound,1,1,40,35,100,0,10,2,1,,5,1,5
        '''2,karate-chop,1,2,50,25,100,0,10,2,44,,5,2,5
        '''3,double-slap,1,1,15,10,85,0,10,2,30,,5,10,7
        '''4,comet-punch,1,1,18,15,85,0,10,2,30,,5,12,7
        '''5,mega-punch,1,1,80,20,85,0,10,2,1,,5,1,18
        '''6,pay-day,1,1,40,20,100,0,10,2,35,,4,11,23
        '''7,fire-punch,1,10,75,15,100,0,10,2,5,10,2,1,17
        '''8,ice-punch,1,15,75,15,100,0,10,2,6 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property moves() As String
            Get
                Return ResourceManager.GetString("moves", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SteinsGate1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SteinsGate1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SteinsGate2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SteinsGate2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SteinsGate3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SteinsGate3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to id,identifier,generation_id,damage_class_id
        '''1,normal,1,2
        '''2,fighting,1,2
        '''3,flying,1,2
        '''4,poison,1,2
        '''5,ground,1,2
        '''6,rock,1,2
        '''7,bug,1,2
        '''8,ghost,1,2
        '''9,steel,2,2
        '''10,fire,1,3
        '''11,water,1,3
        '''12,grass,1,3
        '''13,electric,1,3
        '''14,psychic,1,3
        '''15,ice,1,3
        '''16,dragon,1,3
        '''17,dark,2,3
        '''18,fairy,6,
        '''10001,unknown,2,
        '''10002,shadow,3,.
        '''</summary>
        Friend ReadOnly Property typeid() As String
            Get
                Return ResourceManager.GetString("typeid", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
